/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.uniquindio.view;

import co.edu.uniquindio.bo.Controlador;
import co.edu.uniquindio.entiti.Encuesta;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form FormularioEncuestas
     */
    public Formulario() {
        initComponents();
        listarFactura();
    }
    
    private Controlador encbo = new Controlador();
    
    public void listarFactura() {
        encbo.listarEncuesta(tbFactura);
    }
    
    public void idMax(){
        txtIdFactura.setText(encbo.getMaximoId() + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupTipo = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdFactura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFechaFactura = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtClienteFactura = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rdInactivoFactura = new javax.swing.JRadioButton();
        rdActivoFactura = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbFactura = new javax.swing.JTable();
        btnFinalizarFactura = new javax.swing.JButton();
        btnAgregarFactura = new javax.swing.JButton();
        btnModificarFactura = new javax.swing.JButton();
        btnLimpiarFactura = new javax.swing.JButton();
        btnEliminarFactura = new javax.swing.JButton();
        txtTotalFactura = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtVendedorFactura = new javax.swing.JTextField();
        txtPagoFactura = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/uniquindio/view/Vibrance.PNG"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 390, 500));

        jTabbedPane1.addTab("Inicio", jPanel3);

        jTabbedPane2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1270, 620));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("FACTURA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel2.setText("ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        txtIdFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jPanel1.add(txtIdFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 300, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel3.setText("Fecha:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        txtFechaFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jPanel1.add(txtFechaFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 300, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel4.setText("Total:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel5.setText("Estado:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel6.setText("Pago:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        txtClienteFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jPanel1.add(txtClienteFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 300, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel7.setText("Cliente:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        rdInactivoFactura.setBackground(new java.awt.Color(255, 255, 255));
        groupTipo.add(rdInactivoFactura);
        rdInactivoFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        rdInactivoFactura.setText("Inactivo");
        jPanel1.add(rdInactivoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        rdActivoFactura.setBackground(new java.awt.Color(255, 255, 255));
        groupTipo.add(rdActivoFactura);
        rdActivoFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        rdActivoFactura.setText("Activo");
        rdActivoFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdActivoFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(rdActivoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        tbFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        tbFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbFacturaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbFactura);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 680, 420));

        btnFinalizarFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btnFinalizarFactura.setText("Imprimir Factura");
        btnFinalizarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnFinalizarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 530, -1, -1));

        btnAgregarFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btnAgregarFactura.setText("Agregar");
        btnAgregarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, -1));

        btnModificarFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btnModificarFactura.setText("Modificar");
        btnModificarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, -1, -1));

        btnLimpiarFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btnLimpiarFactura.setText("Limpiar");
        btnLimpiarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, -1, -1));

        btnEliminarFactura.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminarFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btnEliminarFactura.setText("Eliminar");
        btnEliminarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 530, -1, -1));

        txtTotalFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtTotalFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotalFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 300, -1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel9.setText("Vendedor:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        txtVendedorFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtVendedorFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVendedorFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(txtVendedorFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 300, -1));

        txtPagoFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jPanel1.add(txtPagoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 300, -1));

        jPanel4.add(jPanel1);

        jTabbedPane2.addTab("Generar Factura", jPanel4);
        jTabbedPane2.addTab("Historial Factura", jPanel5);
        jTabbedPane2.addTab("Asignar Productos", jPanel6);

        jPanel2.add(jTabbedPane2);

        jTabbedPane1.addTab("Venta", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinalizarFacturaActionPerformed

    private void btnAgregarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFacturaActionPerformed
        if (txtIdFactura.getText().isEmpty() || txtFechaFactura.getText().isEmpty() || txtVendedorFactura.getText().isEmpty() || txtClienteFactura.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Llene los datos");
        } else {
            Integer tipo;
            if (rdInactivoFactura.isSelected()) {
                tipo = 2;
            }else {
                tipo = 1;
            }
            
            Encuesta enc = new Encuesta();
           
            SimpleDateFormat fechaFormato = new SimpleDateFormat("dd-mm-yy");
            
            enc.setId(Integer.parseInt(txtIdFactura.getText()));
            
             try {
            enc.setFechaVenta((java.sql.Date) fechaFormato.parse(txtFechaFactura.getText()));
             } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Error al convertir la fecha: " + e.getMessage());
            }
            enc.setTotalVenta(Double.parseDouble(txtTotalFactura.getText()));
            enc.setVendedorId(Integer.parseInt(txtVendedorFactura.getText()));
            enc.setEstadoId(tipo);
            enc.setPagoId(Integer.parseInt(txtPagoFactura.getText()));
            enc.setClienteCedula(Integer.parseInt(txtClienteFactura.getText()));
            String mensaje = encbo.agregarEncuesta(enc);
            
            JOptionPane.showMessageDialog(null, mensaje);
            
            limpiar();
            listarFactura();
        }
    }//GEN-LAST:event_btnAgregarFacturaActionPerformed

    private void btnModificarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarFacturaActionPerformed
        if (txtIdFactura.getText().isEmpty() || txtFechaFactura.getText().isEmpty() || txtVendedorFactura.getText().isEmpty() || txtClienteFactura.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Llene los datos");
        } else {
            Integer tipo;
            if (rdInactivoFactura.isSelected()) {
                tipo = 2;
            }else {
                tipo = 1;
            }
            
            Encuesta enc = new Encuesta();

            SimpleDateFormat fechaFormato = new SimpleDateFormat("dd-mm-yy");
            
            enc.setId(Integer.parseInt(txtIdFactura.getText()));
            
             try {
            enc.setFechaVenta((java.sql.Date) fechaFormato.parse(txtFechaFactura.getText()));
             } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Error al convertir la fecha: " + e.getMessage());
            }
           // enc.setTotalVenta(Double.parseDouble(txtTotalFactura.getText()));
            enc.setVendedorId(Integer.parseInt(txtVendedorFactura.getText()));
            enc.setEstadoId(tipo);
           // enc.setPagoId(Integer.parseInt(txtPagoFactura.getText()));
            enc.setClienteCedula(Integer.parseInt(txtClienteFactura.getText()));
            String mensaje = encbo.modificarEncuesta(enc);
            
            JOptionPane.showMessageDialog(null, mensaje);
            
            limpiar();
            listarFactura();
        }
    }//GEN-LAST:event_btnModificarFacturaActionPerformed

    private void btnLimpiarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarFacturaActionPerformed
       limpiar();
    }//GEN-LAST:event_btnLimpiarFacturaActionPerformed

    public void limpiar(){
       txtIdFactura.setText("");
       txtFechaFactura.setText("");
       txtTotalFactura.setText("");
       txtVendedorFactura.setText("");
       txtPagoFactura.setText("");
       txtClienteFactura.setText("");
       groupTipo.clearSelection();
    }
    
    private void btnEliminarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFacturaActionPerformed
        if (txtIdFactura.getText().isEmpty() || txtFechaFactura.getText().isEmpty() || txtVendedorFactura.getText().isEmpty() || txtClienteFactura.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Llene los datos");
        } else {
            Encuesta enc = new Encuesta();
            String mensaje = encbo.eliminarEncuesta(Integer.parseInt(txtIdFactura.getText()));
            
            JOptionPane.showMessageDialog(null, mensaje);
            
            limpiar();
            listarFactura();
        }
    }//GEN-LAST:event_btnEliminarFacturaActionPerformed

    private void tbFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFacturaMouseClicked
        int seleccion = tbFactura.rowAtPoint(evt.getPoint());
       txtIdFactura.setText(tbFactura.getValueAt(seleccion, 0) + "");
       txtFechaFactura.setText(tbFactura.getValueAt(seleccion, 1) + "");
       txtTotalFactura.setText(tbFactura.getValueAt(seleccion, 2) + "");
       txtVendedorFactura.setText(tbFactura.getValueAt(seleccion, 3) + "");
       String tipo = tbFactura.getValueAt(seleccion, 4) + "";
        if (tipo.equals("2")) {
            rdInactivoFactura.setSelected(true);
        }else if (tipo.equals("1")) {
            rdActivoFactura.setSelected(true);
        }
       txtPagoFactura.setText(tbFactura.getValueAt(seleccion, 5) + "");
       txtClienteFactura.setText(tbFactura.getValueAt(seleccion, 6) + "");
    }//GEN-LAST:event_tbFacturaMouseClicked

    private void txtTotalFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalFacturaActionPerformed

    private void txtVendedorFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVendedorFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVendedorFacturaActionPerformed

    private void rdActivoFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdActivoFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdActivoFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarFactura;
    private javax.swing.JButton btnEliminarFactura;
    private javax.swing.JButton btnFinalizarFactura;
    private javax.swing.JButton btnLimpiarFactura;
    private javax.swing.JButton btnModificarFactura;
    private javax.swing.ButtonGroup groupTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JRadioButton rdActivoFactura;
    private javax.swing.JRadioButton rdInactivoFactura;
    private javax.swing.JTable tbFactura;
    private javax.swing.JTextField txtClienteFactura;
    private javax.swing.JTextField txtFechaFactura;
    private javax.swing.JTextField txtIdFactura;
    private javax.swing.JTextField txtPagoFactura;
    private javax.swing.JTextField txtTotalFactura;
    private javax.swing.JTextField txtVendedorFactura;
    // End of variables declaration//GEN-END:variables
}
