/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.uniquindio.view;

import co.edu.uniquindio.bo.FacturaControlador;
import co.edu.uniquindio.bo.ProductoControlador;
import co.edu.uniquindio.entiti.Factura;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form FormularioEncuestas
     */
    public Formulario() {
        initComponents();
        listarFactura();
        listarProductosAsignar();
        bloquearComponentes();
    }
    
    private FacturaControlador encbo = new FacturaControlador();
    
    private ProductoControlador probo = new ProductoControlador();
    
    public void listarFactura() {
        encbo.listarFactura(tbFactura);
    }
    
    public void listarProductosAsignar() {
        probo.listarProducto(tbProductoAsignarProducto);
    }
    
    public void idMax(){
        txtIdFactura.setText(encbo.getMaximoId() + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupTipo = new javax.swing.ButtonGroup();
        groupProductoAsignar = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdFactura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFechaFactura = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtClienteFactura = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rdInactivoFactura = new javax.swing.JRadioButton();
        rdActivoFactura = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbFactura = new javax.swing.JTable();
        btnFinalizarFactura = new javax.swing.JButton();
        btnAgregarFactura = new javax.swing.JButton();
        btnModificarFactura = new javax.swing.JButton();
        btnLimpiarFactura = new javax.swing.JButton();
        btnEliminarFactura = new javax.swing.JButton();
        txtTotalFactura = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtVendedorFactura = new javax.swing.JTextField();
        txtPagoFactura = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtIdAsignarProducto = new javax.swing.JTextField();
        txtNombreAsignarProducto = new javax.swing.JTextField();
        txtPrecioVentaAsignarProducto = new javax.swing.JTextField();
        txtCategoriaAsignarProducto = new javax.swing.JTextField();
        txtPromocionAsignarProducto = new javax.swing.JTextField();
        txtFacturaAsignarProducto = new javax.swing.JTextField();
        rdDisponibleAsignarProducto = new javax.swing.JRadioButton();
        rdNoDisponibleAsignarProducto = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDetalleAsignarProducto = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbProductoAsignarProducto = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        txtBuscarAsignarProducto = new javax.swing.JTextField();
        btnBuscarAsignarProducto = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txtCantidadAsignarProducto = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtSubtotalAsignarProducto = new javax.swing.JTextField();
        btnLimpiarAsignarProducto = new javax.swing.JButton();
        btnAsignarProducto = new javax.swing.JButton();
        btnBorrarAsignarProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/uniquindio/view/Vibrance.PNG"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 390, 500));

        jTabbedPane1.addTab("Inicio", jPanel3);

        jTabbedPane2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1270, 620));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("FACTURA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel2.setText("ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        txtIdFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jPanel1.add(txtIdFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 300, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel3.setText("Fecha:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        txtFechaFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtFechaFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(txtFechaFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 300, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel4.setText("Total:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel5.setText("Estado:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel6.setText("Pago:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        txtClienteFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jPanel1.add(txtClienteFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 300, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel7.setText("Cliente:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        rdInactivoFactura.setBackground(new java.awt.Color(255, 255, 255));
        groupTipo.add(rdInactivoFactura);
        rdInactivoFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        rdInactivoFactura.setText("Inactivo");
        jPanel1.add(rdInactivoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        rdActivoFactura.setBackground(new java.awt.Color(255, 255, 255));
        groupTipo.add(rdActivoFactura);
        rdActivoFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        rdActivoFactura.setText("Activo");
        rdActivoFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdActivoFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(rdActivoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        tbFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        tbFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbFacturaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbFactura);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 700, 330));

        btnFinalizarFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btnFinalizarFactura.setText("Imprimir Factura");
        btnFinalizarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnFinalizarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 520, -1, -1));

        btnAgregarFactura.setBackground(new java.awt.Color(0, 204, 102));
        btnAgregarFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btnAgregarFactura.setText("Agregar");
        btnAgregarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        btnModificarFactura.setBackground(new java.awt.Color(255, 255, 0));
        btnModificarFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btnModificarFactura.setText("Modificar");
        btnModificarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, -1, -1));

        btnLimpiarFactura.setBackground(new java.awt.Color(0, 204, 102));
        btnLimpiarFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btnLimpiarFactura.setText("Limpiar");
        btnLimpiarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, -1, -1));

        btnEliminarFactura.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminarFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btnEliminarFactura.setText("Eliminar");
        btnEliminarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 520, -1, -1));

        txtTotalFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtTotalFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotalFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 300, -1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel9.setText("Vendedor:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        txtVendedorFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtVendedorFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVendedorFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(txtVendedorFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 300, -1));

        txtPagoFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jPanel1.add(txtPagoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 300, -1));

        jPanel4.add(jPanel1);

        jTabbedPane2.addTab("Generar Factura", jPanel4);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setText("ASIGNAR PRODUCTOS A LA FACTURA");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel11.setText("ID:");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel12.setText("Nombre:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel13.setText("Precio Venta:");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel14.setText("Categoria:");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel18.setText("Promocion:");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel20.setText("Estado:");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel21.setText("Factura:");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        txtIdAsignarProducto.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtIdAsignarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdAsignarProductoActionPerformed(evt);
            }
        });
        jPanel5.add(txtIdAsignarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 300, -1));

        txtNombreAsignarProducto.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtNombreAsignarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAsignarProductoActionPerformed(evt);
            }
        });
        jPanel5.add(txtNombreAsignarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 300, -1));

        txtPrecioVentaAsignarProducto.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jPanel5.add(txtPrecioVentaAsignarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 300, -1));

        txtCategoriaAsignarProducto.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jPanel5.add(txtCategoriaAsignarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 300, -1));

        txtPromocionAsignarProducto.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jPanel5.add(txtPromocionAsignarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 300, -1));

        txtFacturaAsignarProducto.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jPanel5.add(txtFacturaAsignarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 300, -1));

        rdDisponibleAsignarProducto.setBackground(new java.awt.Color(255, 255, 255));
        groupProductoAsignar.add(rdDisponibleAsignarProducto);
        rdDisponibleAsignarProducto.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        rdDisponibleAsignarProducto.setText("Disponible");
        jPanel5.add(rdDisponibleAsignarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        rdNoDisponibleAsignarProducto.setBackground(new java.awt.Color(255, 255, 255));
        groupProductoAsignar.add(rdNoDisponibleAsignarProducto);
        rdNoDisponibleAsignarProducto.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        rdNoDisponibleAsignarProducto.setText("No Disponible");
        jPanel5.add(rdNoDisponibleAsignarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        tbDetalleAsignarProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbDetalleAsignarProducto);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 60, 670, 240));

        tbProductoAsignarProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbProductoAsignarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProductoMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbProductoAsignarProducto);

        jPanel5.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 670, 260));

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel22.setText("Buscar:");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        txtBuscarAsignarProducto.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        jPanel5.add(txtBuscarAsignarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 300, -1));

        btnBuscarAsignarProducto.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btnBuscarAsignarProducto.setText("Buscar");
        jPanel5.add(btnBuscarAsignarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, -1, -1));

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel23.setText("Cantidad:");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        txtCantidadAsignarProducto.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jPanel5.add(txtCantidadAsignarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 300, -1));

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel24.setText("Subtotal:");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        txtSubtotalAsignarProducto.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jPanel5.add(txtSubtotalAsignarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 300, -1));

        btnLimpiarAsignarProducto.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btnLimpiarAsignarProducto.setText("Limpiar");
        btnLimpiarAsignarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarAsignarProductoActionPerformed(evt);
            }
        });
        jPanel5.add(btnLimpiarAsignarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, -1, -1));

        btnAsignarProducto.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btnAsignarProducto.setText("Asignar");
        jPanel5.add(btnAsignarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        btnBorrarAsignarProducto.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btnBorrarAsignarProducto.setText("Borrar");
        jPanel5.add(btnBorrarAsignarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, -1, -1));

        jScrollPane1.setViewportView(jPanel5);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 590));

        jTabbedPane2.addTab("Asignar Productos", jPanel6);

        jPanel2.add(jTabbedPane2);

        jTabbedPane1.addTab("Venta", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinalizarFacturaActionPerformed

    private void btnAgregarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFacturaActionPerformed
        if (txtIdFactura.getText().isEmpty() || txtVendedorFactura.getText().isEmpty() || txtClienteFactura.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Llene los datos");
        } else {
            Integer tipo;
            if (rdInactivoFactura.isSelected()) {
                tipo = 2;
            }else {
                tipo = 1;
            }
            
            Factura enc = new Factura();
           
             LocalDate fechaLocal = LocalDate.now();
             java.sql.Date fecha = java.sql.Date.valueOf(fechaLocal);
            
            //SimpleDateFormat fechaFormato = new SimpleDateFormat("dd-mm-yy");
            
            enc.setId(Integer.parseInt(txtIdFactura.getText()));
            
            enc.setFechaVenta(fecha);
            if (txtTotalFactura.getText().isEmpty()) {
                Double total = null;
                 enc.setTotalVenta(total);
            } else {
                 enc.setTotalVenta(Double.parseDouble(txtTotalFactura.getText()));
            }
           
            enc.setVendedorId(Integer.parseInt(txtVendedorFactura.getText()));
            enc.setEstadoId(tipo);
            
            if (txtPagoFactura.getText().isEmpty()) {
                Integer pago = null;
                enc.setPagoId(pago);
            }else {
                enc.setPagoId(Integer.parseInt(txtPagoFactura.getText()));
            }
            
            enc.setClienteCedula(Integer.parseInt(txtClienteFactura.getText()));
            String mensaje = encbo.agregarFactura(enc);
            
            JOptionPane.showMessageDialog(null, mensaje);
            
            limpiar();
            listarFactura();
        }
    }//GEN-LAST:event_btnAgregarFacturaActionPerformed

    private void btnModificarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarFacturaActionPerformed
        if (txtIdFactura.getText().isEmpty() || txtVendedorFactura.getText().isEmpty() || txtClienteFactura.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Llene los datos");
        } else {
            Integer tipo;
            if (rdInactivoFactura.isSelected()) {
                tipo = 2;
            }else {
                tipo = 1;
            }
            
            Factura enc = new Factura();

             LocalDate fechaLocal = LocalDate.now();
             java.sql.Date fecha = java.sql.Date.valueOf(fechaLocal);
            
            //SimpleDateFormat fechaFormato = new SimpleDateFormat("dd-mm-yy");
            
            enc.setId(Integer.parseInt(txtIdFactura.getText()));
            
             enc.setFechaVenta(fecha);
            if (txtTotalFactura.getText().isEmpty()) {
                Double total = null;
                 enc.setTotalVenta(total);
            } else {
                 enc.setTotalVenta(Double.parseDouble(txtTotalFactura.getText()));
            }
           
            enc.setVendedorId(Integer.parseInt(txtVendedorFactura.getText()));
            enc.setEstadoId(tipo);
            
            if (txtPagoFactura.getText().isEmpty()) {
                Integer pago = null;
                enc.setPagoId(pago);
            }else {
                enc.setPagoId(Integer.parseInt(txtPagoFactura.getText()));
            }
            
            enc.setClienteCedula(Integer.parseInt(txtClienteFactura.getText()));
            String mensaje = encbo.modificarFactura(enc);
            
            JOptionPane.showMessageDialog(null, mensaje);
            
            limpiar();
            listarFactura();
        }
    }//GEN-LAST:event_btnModificarFacturaActionPerformed

    private void btnLimpiarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarFacturaActionPerformed
       limpiar();
    }//GEN-LAST:event_btnLimpiarFacturaActionPerformed

    public void limpiar(){
       txtIdFactura.setText("");
       txtFechaFactura.setText("");
       txtTotalFactura.setText("");
       txtVendedorFactura.setText("");
       txtPagoFactura.setText("");
       txtClienteFactura.setText("");
       groupTipo.clearSelection();
    }
    
    public void bloquearComponentes(){
        txtFechaFactura.setEnabled(false);
        txtIdAsignarProducto.setEnabled(false);
        txtNombreAsignarProducto.setEnabled(false);
        txtPrecioVentaAsignarProducto.setEnabled(false);
        txtCategoriaAsignarProducto.setEnabled(false);
        txtPromocionAsignarProducto.setEnabled(false);
        rdDisponibleAsignarProducto.setEnabled(false);
        rdNoDisponibleAsignarProducto.setEnabled(false);
        txtSubtotalAsignarProducto.setEnabled(false);
    }
    
    private void btnEliminarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFacturaActionPerformed
        if (txtIdFactura.getText().isEmpty() || txtVendedorFactura.getText().isEmpty() || txtClienteFactura.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Llene los datos");
        } else {
            Factura enc = new Factura();
            String mensaje = encbo.eliminarFactura(Integer.parseInt(txtIdFactura.getText()));
            
            JOptionPane.showMessageDialog(null, mensaje);
            
            limpiar();
            listarFactura();
        }
    }//GEN-LAST:event_btnEliminarFacturaActionPerformed

    private void tbFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFacturaMouseClicked
       int seleccion = tbFactura.rowAtPoint(evt.getPoint());
       txtIdFactura.setText(tbFactura.getValueAt(seleccion, 0) + "");
       txtFechaFactura.setText(tbFactura.getValueAt(seleccion, 1) + "");
        if ((tbFactura.getValueAt(seleccion, 2) + "").equals("null")) {
            txtTotalFactura.setText("");
        }else {
            txtTotalFactura.setText(tbFactura.getValueAt(seleccion, 2) + "");
        }
       
       txtVendedorFactura.setText(tbFactura.getValueAt(seleccion, 3) + "");
       String tipo = tbFactura.getValueAt(seleccion, 4) + "";
        if (tipo.equals("2")) {
            rdInactivoFactura.setSelected(true);
        }else if (tipo.equals("1")) {
            rdActivoFactura.setSelected(true);
        }
        
        if ((tbFactura.getValueAt(seleccion, 5) + "").equals("null")) {
            txtPagoFactura.setText("");
        } else {
            txtPagoFactura.setText(tbFactura.getValueAt(seleccion, 5) + "");
        }
       
       txtClienteFactura.setText(tbFactura.getValueAt(seleccion, 6) + "");
    }//GEN-LAST:event_tbFacturaMouseClicked

    private void txtTotalFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalFacturaActionPerformed

    private void txtVendedorFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVendedorFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVendedorFacturaActionPerformed

    private void rdActivoFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdActivoFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdActivoFacturaActionPerformed

    private void txtFechaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaFacturaActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaFacturaActionPerformed

    private void txtIdAsignarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdAsignarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdAsignarProductoActionPerformed

    private void txtNombreAsignarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAsignarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAsignarProductoActionPerformed

    private void btnLimpiarAsignarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarAsignarProductoActionPerformed
        txtIdAsignarProducto.setText("");
        txtNombreAsignarProducto.setText("");
        txtPrecioVentaAsignarProducto.setText("");
        txtCategoriaAsignarProducto.setText("");
        txtPromocionAsignarProducto.setText("");
        rdDisponibleAsignarProducto.setText("");
        rdNoDisponibleAsignarProducto.setText("");
        txtFacturaAsignarProducto.setText("");
        txtCantidadAsignarProducto.setText("");
        txtSubtotalAsignarProducto.setText("");
    }//GEN-LAST:event_btnLimpiarAsignarProductoActionPerformed

    private void tbProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProductoMouseClicked
       int seleccion = tbProductoAsignarProducto.rowAtPoint(evt.getPoint());
       txtIdAsignarProducto.setText(tbProductoAsignarProducto.getValueAt(seleccion, 0) + "");
       txtNombreAsignarProducto.setText(tbProductoAsignarProducto.getValueAt(seleccion, 1) + "");
       txtPrecioVentaAsignarProducto.setText(tbProductoAsignarProducto.getValueAt(seleccion, 2) + "");
       txtCategoriaAsignarProducto.setText(tbProductoAsignarProducto.getValueAt(seleccion, 3) + "");
       txtPromocionAsignarProducto.setText(tbProductoAsignarProducto.getValueAt(seleccion, 4) + "");
               
        String tipo = tbProductoAsignarProducto.getValueAt(seleccion, 5) + "";
        if (tipo.equals("2")) {
            rdNoDisponibleAsignarProducto.setSelected(true);
        }else if (tipo.equals("1")) {
            rdDisponibleAsignarProducto.setSelected(true);
        } 
    }//GEN-LAST:event_tbProductoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarFactura;
    private javax.swing.JButton btnAsignarProducto;
    private javax.swing.JButton btnBorrarAsignarProducto;
    private javax.swing.JButton btnBuscarAsignarProducto;
    private javax.swing.JButton btnEliminarFactura;
    private javax.swing.JButton btnFinalizarFactura;
    private javax.swing.JButton btnLimpiarAsignarProducto;
    private javax.swing.JButton btnLimpiarFactura;
    private javax.swing.JButton btnModificarFactura;
    private javax.swing.ButtonGroup groupProductoAsignar;
    private javax.swing.ButtonGroup groupTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JRadioButton rdActivoFactura;
    private javax.swing.JRadioButton rdDisponibleAsignarProducto;
    private javax.swing.JRadioButton rdInactivoFactura;
    private javax.swing.JRadioButton rdNoDisponibleAsignarProducto;
    private javax.swing.JTable tbDetalleAsignarProducto;
    private javax.swing.JTable tbFactura;
    private javax.swing.JTable tbProductoAsignarProducto;
    private javax.swing.JTextField txtBuscarAsignarProducto;
    private javax.swing.JTextField txtCantidadAsignarProducto;
    private javax.swing.JTextField txtCategoriaAsignarProducto;
    private javax.swing.JTextField txtClienteFactura;
    private javax.swing.JTextField txtFacturaAsignarProducto;
    private javax.swing.JTextField txtFechaFactura;
    private javax.swing.JTextField txtIdAsignarProducto;
    private javax.swing.JTextField txtIdFactura;
    private javax.swing.JTextField txtNombreAsignarProducto;
    private javax.swing.JTextField txtPagoFactura;
    private javax.swing.JTextField txtPrecioVentaAsignarProducto;
    private javax.swing.JTextField txtPromocionAsignarProducto;
    private javax.swing.JTextField txtSubtotalAsignarProducto;
    private javax.swing.JTextField txtTotalFactura;
    private javax.swing.JTextField txtVendedorFactura;
    // End of variables declaration//GEN-END:variables
}
